version: '3.9'

services:

  front-end:
    build:
      context: ../../material-applications//example-frontend
      dockerfile: Dockerfile_front
    container_name: front-end-container

  back-end:
    build:
      context: ../../material-applications/example-backend
      dockerfile: Dockerfile_back
    environment:
      - REDIS_HOST=redis
      - POSTGRES_HOST=db
      - POSTGRES_PASSWORD=example
    depends_on:
      - db
    container_name: back-end-container

  redis:
    image: redis
    command: redis-server
    container_name: redis-server

  db:
    image: postgres
    restart: unless-stopped
    environment:
      - POSTGRES_PASSWORD=example
    volumes:
      - database:/var/lib/postgres/data
    container_name: postgres-db

  proxy: 
    image: nginx
    volumes: 
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports: 
      - 5000:80 
    depends_on:
      - front-end
      - back-end

volumes:
  database:
