version: '3.9'

services:
  front-end:
    build:
      context: ./ml-kurkkumopo-frontend
    ports:
      - 3000:3000
    container_name: front-end
  back-end:
    build:
      context: ./ml-kurkkumopo-backend
    ports:
      - 5000:5000
    volumes:
      - model:/src/model
    depends_on:
      - training
    container_name: back-end
  training:
    build:
      context: ./ml-kurkkumopo-training
    volumes:
      - model:/src/model
      - image:/src/imgs
      - data:/src/data
    container_name: training

volumes:
  model:
  image:
  data: