version: '3.9'

services:
  front-end:
    build: ../2.3/front/example-frontend
    ports:
      - 5000:5000
    container_name: front-end-container
  back-end:
    build: ../2.3/back/example-backend
    environment:
      - REDIS_HOST=redis
    ports:
      - 8080:8080
    container_name: back-end-container
  redis:
    image: redis

    command: redis-server
    container_name: redis-server  

  
  
    